development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:00f4c42133ce6a073313666bb8975cba@crestfish.redistogo.com:9287/
  channel_prefix: message_me_production
